Metrics/LineLength:
  Max: 400

Metrics/MethodLength: 
  Max: 200

Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false
